CREATE TABLE IF NOT EXISTS reglementari (
  id INT NOT NULL AUTO_INCREMENT,
  indicativ VARCHAR(80) NOT NULL,
  an INT NOT NULL,
  tip_reglementare VARCHAR(80) NOT NULL,
  tip_document VARCHAR(40) NOT NULL DEFAULT 'informatie',
  disciplina VARCHAR(120) NOT NULL,
  domeniu VARCHAR(180) NOT NULL,
  descriere_nume_fisier VARCHAR(180) NOT NULL DEFAULT '',
  actualizeaza_indicativ VARCHAR(1000) NOT NULL DEFAULT '',
  tip_cladire VARCHAR(180) NOT NULL,
  descriere TEXT NOT NULL,
  denumire_exacta VARCHAR(500) NOT NULL,
  limba VARCHAR(8) NOT NULL,
  nume_fisier VARCHAR(260) NOT NULL,
  cale_fisier VARCHAR(1000) NOT NULL,
  data_adaugare DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY reglementari_indicativ_an_unique (indicativ, an),
  KEY reglementari_tip_idx (tip_reglementare),
  KEY reglementari_disciplina_idx (disciplina),
  KEY reglementari_limba_idx (limba)
);
