export const regulationTypes = [
  "normative",
  "norme (NP, NT, NM, NTE)",
  "prescripții tehnice (IT, ST, PT)",
  "ghiduri (GP, SC, GT)",
  "standarde",
  "curs, publicații",
  "îndrumătoare",
  "legi",
  "manuale",
  "metodologii",
  "ordin (OIG, OUG, OM, OG, HG)",
  "diverse",
] as const;

export const disciplines = [
  "administrativ",
  "arhitectură",
  "construcții",
  "general",
  "instalații",
  "instalații acustice",
  "instalații curenți slabi",
  "instalații de desfumare",
  "instalații de detecție",
  "instalații de gaze medicale",
  "instalații combustibil",
  "instalații electrice",
  "instalații sanitare",
  "instalații termice",
  "instalații ventilare",
  "manualul instalatorului",
  "performanță energetică",
  "protecție la incendiu",
  "protecția mediului",
  "protecția muncii",
  "rețele apă-canal",
  "rețele de incintă",
  "rețele electrice",
  "rețele termice",
  "rețele de utilități",
  "situații de urgență",
] as const;

export const languages = ["RO", "EN", "FR"] as const;

export const documentTypes = [
  "legislatie",
  "informatie",
  "tehnic",
] as const;

export const domainOptions = [
  "administrativ",
  "birouri",
  "centru date",
  "clădiri înalte",
  "educație",
  "general",
  "horeca",
  "industrial",
  "medical",
  "parcaje auto",
  "piscină",
  "rezidențial",
  "retail",
  "săli aglomerate",
  "săli audiție",
  "specifice",
  "vârstnici",
] as const;
